NOVOS = ["NOVO", "NOVO - VIVO TOTAL"]
PORTABILIDADE = [
    "PORTABILIDADE PF + TT PF/PJ",
    "PORTABILIDADE",
    "PORTABILIDADE - VIVO TOTAL",
    "PORTABILIDADE PF + TT PF/PJ - VIVO TOTAL",
    "PORTABILIDADE FWT",
]

JA_CLIENTE = ["JÁ CLIENTE"]
MIGRACAO_PRE_POS = ["MIGRAÇÃO PRÉ/PÓS", "MIGRAÇÃO PRÉ/PÓS - VIVO TOTAL"]
AVANCADA = ["AVANÇADA"]

CONCLUIDOS_MOVEL = ["CONCLUIDO", "FATURANDO-PORTABILIDADE"]
CONCLUIDOS_FIXA = ["ATIVO"]
