NOVOS = ["NOVO", "NOVO - VIVO TOTAL"]
PORTABILIDADE = [
    "PORTABILIDADE PF + TT PF/PJ",
    "PORTABILIDADE",
    "PORTABILIDADE - VIVO TOTAL",
    "PORTABILIDADE PF + TT PF/PJ - VIVO TOTAL",
    "PORTABILIDADE FWT",
]

JA_CLIENTE = ["JÁ CLIENTE"]
MIGRACAO_PRE_POS = ["MIGRAÇÃO PRÉ/PÓS", "MIGRAÇÃO PRÉ/PÓS - VIVO TOTAL"]
AVANCADA = ["AVANÇADA"]

CONCLUIDOS_MOVEL = ["CONCLUIDO", "FATURANDO-PORTABILIDADE"]
CONCLUIDOS_FIXA = ["ATIVO"]


CONSULTORES_MULTIPLICADOR_PADRAO = [
    "CAIQUE RIBEIRO GUEDES",
    "LUCAS ANDRE",
    "LUCAS DE JESUS ALVES GUALBERTO",
    "LUCAS FIGUEREDO",
    "ORLANDO RODRIGUES DA SILVA",
    "PEDRO HENRIQUE",
    "MARIANE GONÇALVES TEIXEIRA",
    "THATILA ALVES XIMENES",
    "PAMARA ROSA"
]